pipeline:

########################################
# publish to DTR on merge into master #
########################################

  publish:
    image: plugins/docker
    repo: dtr.int-ac.dvla.gov.uk/vehicle-reg-num/government-gateway-stub
    registry: dtr.int-ac.dvla.gov.uk
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    build_args:
      - GIT_COMMIT_TAG=${DRONE_COMMIT_SHA}
      - VERSION=${DRONE_TAG=${DRONE_COMMIT_SHA:0:6}}
      - BUILD_NO=${DRONE_BUILD_NUMBER}
    tags:
      - "${DRONE_TAG=latest}"
      - "${DRONE_COMMIT_SHA}"
    when:
      ref:
        - refs/heads/master
        - refs/tags/*
      event:
        - push
        - tag

  #############################################################
  # Deploy to K8S                                            ##
  #############################################################
  deploy government-gateway-stub image to Squad3 dev k8s:
    image: quay.io/ipedrazas/drone-helm:k1.8.1-h2.7.0
    chart: ./deployment
    skip_tls_verify: true
    release: government-gateway-stub
    namespace: pr-sales
    debug: true
    wait: false
    values_files:
      - "./deployment/values.yaml"
      - "./deployment/dev-values.yaml"
    values: image.tag=${DRONE_COMMIT_SHA}
    prefix: dev
    secrets: [ dev_service_account, dev_api_server, dev_kubernetes_token ]
    when:
      branch: master
      event: push


  ############################################
  ## Slack build status (Drone - on failure) #
  ############################################
  slack push failure:
    channel: squad3_builds
    image: plugins/slack
    secrets:
      - slack_webhook
    template: |
      government-gateway-stub: drone event {{build.event}} has failed!
      Build - {{build.number}}
      Branch - {{build.branch}}
      Author - {{build.author}}
      Fix me please! <{{build.link}}|Details>
    username: drone
    when:
      branch:
        exclude:
          - feature/*
      event: push
      status:
        - failure
