version: '3'
services:
  mock_user_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=9090
      - STUB_CLIENT_ID=stubOidcClient
      - STUB_CLIENT_SECRET=secretsarehardtokeep
      - AUTH_CALLBACKS=http://localhost:3000/auth/gg/callback, http://0.0.0.0:3000/auth/gg/callback
      - TEST_USER_NAME="TestName TestEmail"
      - TEST_USER_EMAIL="testname@testprovider.com"
      - SERVICE_RETURN_URL="http://localhost:3000"
    ports:
      - 9090:9090
