version: '3'
services:
  mock_user_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=9090
      - CLIENT_ID=my-client
      - CLIENT_SECRET=my-secret
      - CLIENT_REDIRECT_URI=https://prs-shop-dev.squad3.ac.dvla.gov.uk
      - CLIENT_LOGOUT_REDIRECT_URI=http://localhost:9090
    ports:
      - 9090:9090
