version: '3'
services:
  mock_user_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=9090
      - STUB_CLIENT_ID=stubOidcClient
      - STUB_CLIENT_SECRET=secretsarehardtokeep
      - AUTH_CALLBACK=http://localhost:3000/auth/gg/callback
      - TEST_USER_NAME="TestName TestEmail"
      - TEST_USER_EMAIL="testname@testprovider.com"
    ports:
      - 9090:9090
