apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "government-gateway-stub.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "government-gateway-stub.name" . }}
    chart: {{ template "government-gateway-stub.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "government-gateway-stub.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "government-gateway-stub.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: dtr-int-squad3-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 20
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: NODE_ENV
              value: hosted
            - name: STUB_CLIENT_ID
              value: {{ .Values.service.clientId | quote }}
            - name: STUB_CLIENT_SECRET
              value: {{ .Values.service.clientSecret | quote }}
            - name: AUTH_CALLBACKS
              value: {{ .Values.service.authCallbackUrls | quote }}            
            - name: SERVICE_RETURN_URL
              value: {{ .Values.service.serviceReturlUrl | quote }}
            - name: ISSUER
              value: {{ .Values.service.issuer | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
