apiVersion: v1
kind: Service
metadata:
  name: {{ template "government-gateway-stub.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    dns.alpha.kubernetes.io/external: {{ .Values.service.dnsName }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 	arn:aws:acm:eu-west-2:959435635375:certificate/2152f4ee-03a1-4fee-aa78-008c443d736c
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  labels:
    app: {{ template "government-gateway-stub.name" . }}
    chart: {{ template "government-gateway-stub.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
  loadBalancerSourceRanges:
    - 62.254.184.134/32
    - 52.56.213.174/32
    # IP addresses to allow access from drone to run acceptance tests.
    - 35.178.21.121/32
    - 35.176.250.206/32
    - 35.177.59.13/32
    - 35.177.66.50/32 # dev egress IP
    - 35.177.33.151/32 # dev egress IP
  selector:
    app: {{ template "government-gateway-stub.name" . }}
    release: {{ .Release.Name }}
